name: alkfred

services:
  alkfred:
    build: .
    working_dir: /app/src
    command: ["sleep","infinity","bash"]   # keeps a shell for exec; you can override per-run
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      # choose ONE of these depending on where your .env is:
      # - ./.env:/app/.env:ro
      - ./src/.env:/app/.env:ro
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: /app/src
